name: 'Push Scenarios'
description: 'Push Scenarios to Azure Health Bot API'
inputs:
  tenant-name:
    description: 'Azure Health Bot Tenant Name'
    required: true
  api-secret:
    description: 'API JWT Secret from Health Bot'
    required: true
  template-file:
    description: 'JSON file containing templates to push'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'